CPRA classification pipeline, rebuilt on C3PA (Bin Musa et al., EMNLP 2024) as the primary dataset instead of synthetic data. Real, expert-annotated privacy policy text from 399 companies. Six of the original eight labels have a defensible mapping to C3PA's taxonomy; Right_to_Access and Risk_Assessment have no equivalent and are dropped from this version of the study, not scored as failures.

In [ ]:
!pip install -q transformers datasets torch scikit-learn pandas numpy matplotlib lime shap

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for lime (setup.py) ... done

Import libraries and set a global random seed of 42 for reproducibility.

In [ ]:

import pandas as pd
import numpy as np
import random
import torch
import re
import warnings
warnings.filterwarnings('ignore')

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed_all(42)

from collections import Counter
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import MultiLabelBinarizer
# from sklearn.metrics import classification_report, f1_score
from sklearn.metrics import classification_report, f1_score, precision_score

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)

print('All imports loaded successfully')
print('Transformers:', __import__('transformers').__version__)
print('PyTorch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())

All imports loaded successfully
Transformers: 5.16.1
PyTorch: 2.11.0+cu128
CUDA available: True

Define the six CPRA labels this study now covers, each with the same written definition used throughout the rest of this work. Right_to_Access and Risk_Assessment were dropped: neither has a defensible equivalent in C3PA's label taxonomy.

In [ ]:
# BLOCK 3: Define canonical 6-label CPRA schema - single source of truth
ALL_LABELS = [
    'Notice_Requirement',
    'Right_to_Correct',
    'Right_to_Delete',
    'Right_to_Know',
    'Right_to_Limit_Sensitive',
    'Right_to_Opt_Out',
]

LABEL_DEFINITIONS = {
    'Right_to_Know':
        'General right to be informed about data practices and usage in a non-procedural way. '
        'Covers transparency, awareness, and informational rights about what data is collected and how it is used.',
    'Right_to_Delete':
        'Right to request that a business delete personal information collected from the consumer.',
    'Right_to_Correct':
        'Right to request correction of inaccurate personal information held by a business.',
    'Right_to_Opt_Out':
        'Right to opt out of the sale or sharing of personal information.',
    'Right_to_Limit_Sensitive':
        'Right to direct a business to limit the use of sensitive personal information.',
    'Notice_Requirement':
        'Legal obligation to actively inform or notify users before or during data collection or processing. '
        'Covers at-collection disclosures, privacy notices, and required transparency procedures, '
        'including what categories of data are collected, shared, or sold.',
}

NUM_LABELS = len(ALL_LABELS)
print(f'{NUM_LABELS} labels defined:', ALL_LABELS)

6 labels defined: ['Notice_Requirement', 'Right_to_Correct', 'Right_to_Delete', 'Right_to_Know', 'Right_to_Limit_Sensitive', 'Right_to_Opt_Out']

Clone the real C3PA dataset and load the raw annotations, preserving genuine multi-label structure. Map C3PA's category taxonomy onto this study's 6 labels, built by comparing each C3PA category directly against LABEL_DEFINITIONS above, not by searching for whichever mapping produced the most data.

In [ ]:
# BLOCK 4: Load C3PA and map to CPRA schema
# Citation: Bin Musa, M., Winston, S. M., Allen, G., Schiller, J., Moore, K., Quick, S.,
# Melvin, J., Srinivasan, P., Diamantis, M. E., & Nithyanand, R. (2024). C3PA: An Open
# Dataset of Expert-Annotated and Regulation-Aware Privacy Policies to Enable Scalable
# Regulatory Compliance Audits. EMNLP 2024. arXiv:2410.03925.

import subprocess, os, glob

if not os.path.exists("C3PA_Dataset"):
    subprocess.run(["git", "clone", "https://github.com/MaazBinMusa/C3PA_Dataset.git"], check=True)

records = []
for subset in ["DB", "WS"]:
    folder = f"C3PA_Dataset/Annotations/{subset}"
    for fp in glob.glob(os.path.join(folder, "*.csv")):
        doc_id = f"{subset}_{os.path.basename(fp).replace('.csv', '')}"
        try:
            df_c3pa = pd.read_csv(fp, on_bad_lines="skip")
        except Exception:
            continue
        cols = {c.lower(): c for c in df_c3pa.columns}
        if "text" not in cols or "label" not in cols:
            continue
        valid = df_c3pa[[cols["text"], cols["label"]]].dropna()
        for text, label in zip(valid[cols["text"]], valid[cols["label"]]):
            text_s, label_s = str(text).strip(), str(label).strip()
            if text_s and label_s and label_s.lower() != "nan":
                records.append({"doc_id": doc_id, "text": text_s, "label": label_s})

c3pa_raw = pd.DataFrame(records)
print(f"Raw C3PA annotation rows: {len(c3pa_raw)}")

# Label mapping - revised after direct comparison against LABEL_DEFINITIONS.
# "Categories of Personal Information Collected/Shared/Sold" map to Notice_Requirement
# because disclosing what data is collected IS the at-collection notice obligation
# in the definition above. "Right to Non-discrimination" is not in this study's
# schema and is deliberately left unmapped.
C3PA_LABEL_MAP = {
    "Description of Right to Correct Information": "Right_to_Correct",
    "Description of Right to Delete": "Right_to_Delete",
    "Description of Right to Opt-out of sale of PI": "Right_to_Opt_Out",
    "Description of Right to Limit use of PI": "Right_to_Limit_Sensitive",
    "Description of Right to Know PI Collected": "Right_to_Know",
    "Description of Right to Know PI sold / shared": "Right_to_Know",
    "Categories of Personal Information Collected": "Notice_Requirement",
    "Categories of Personal Information Shared / Disclosed": "Notice_Requirement",
    "Categories of Personal Information Sold": "Notice_Requirement",
    "Updated Privacy Policy": "Notice_Requirement",
}

c3pa_raw['mapped_label'] = c3pa_raw['label'].map(C3PA_LABEL_MAP)
mapped_only = c3pa_raw.dropna(subset=['mapped_label'])

df_master = (
    mapped_only.groupby(['doc_id', 'text'])['mapped_label']
    .apply(lambda x: sorted(set(x)))
    .reset_index()
    .rename(columns={'mapped_label': 'labels'})
)

print(f"Unique mapped (doc, text) spans before dedup: {len(df_master)}")

# [LEAKAGE FIX] Real privacy policies reuse identical boilerplate text across
# different companies (standard cookie-consent language, standard CCPA disclosure
# clauses), most likely from shared legal template providers. Document-level
# grouping alone does not catch this, since it is the same sentence independently
# appearing in a DIFFERENT document, not one document's content leaking into
# another. Deduplicating by text globally, before the split, removes this risk
# entirely. A small number of duplicated texts (32) had inconsistent labels across
# occurrences; keeping the first occurrence resolves this by picking one label set
# per unique sentence, a standard, disclosed tradeoff.
before_dedup = len(df_master)
df_master = df_master.drop_duplicates(subset='text', keep='first').reset_index(drop=True)
print(f"Removed {before_dedup - len(df_master)} duplicate text rows (shared boilerplate across companies)")

print(f"Unique mapped (doc, text) spans after dedup: {len(df_master)}")
print(f"Unique source documents: {df_master['doc_id'].nunique()}")
print(f"Multi-label spans (2+ labels): {(df_master['labels'].apply(len) > 1).sum()}")

Raw C3PA annotation rows: 45121
Unique mapped (doc, text) spans before dedup: 26740
Removed 992 duplicate text rows (shared boilerplate across companies)
Unique mapped (doc, text) spans after dedup: 25748
Unique source documents: 399
Multi-label spans (2+ labels): 510

Split into training, validation, and test sets by document, not by row. All text spans from the same company's privacy policy stay in one partition, which prevents leakage the same way seed-level grouping did for the synthetic pipeline.

In [ ]:
# [SCALE EXPERIMENT] Subsample to 30% of documents - a lower-resource point than the
# existing 50/70/80 runs, extending the trend toward the data-scarce end. The gap
# between LegalBERT and vanilla BERT was +0.0304 at 50%, +0.0188 at 70%, and -0.0019
# at 80%. This tests whether the gap is even larger below 50%, which would make the
# full trend (30 -> 50 -> 70 -> 80) a more compelling, wider-range demonstration.
# Real counts at 30% (119 of 399 documents, 7,167 rows): thinnest label,
# Right_to_Limit_Sensitive, has 75 rows across 41 of 119 documents - checked in
# advance for document-level coverage, since a 20% version was considered and
# rejected for having too few documents (31) containing this label to split safely.
random.seed(42)
_all_docs_full = sorted(df_master['doc_id'].unique())
_n_docs_keep = int(len(_all_docs_full) * 0.30)
_docs_keep = set(random.sample(_all_docs_full, _n_docs_keep))
df_master = df_master[df_master['doc_id'].isin(_docs_keep)].reset_index(drop=True)
print(f"Subsampled to {len(_docs_keep)} documents ({len(df_master)} rows) - 30% scale experiment.")

# BLOCK 5: Document-level train / validation / test split
mlb = MultiLabelBinarizer(classes=ALL_LABELS)
y_all = mlb.fit_transform(df_master['labels'])
X_all = df_master['text'].values
doc_ids_all = df_master['doc_id'].values

random.seed(42)
unique_docs = sorted(df_master['doc_id'].unique())
shuffled_docs = unique_docs.copy()
random.shuffle(shuffled_docs)

n = len(shuffled_docs)
n_train = int(n * 0.70)
n_val   = int(n * 0.15)

train_docs = set(shuffled_docs[:n_train])
val_docs   = set(shuffled_docs[n_train:n_train + n_val])
test_docs  = set(shuffled_docs[n_train + n_val:])

assert train_docs.isdisjoint(val_docs), 'Leakage: train <-> val'
assert train_docs.isdisjoint(test_docs), 'Leakage: train <-> test'
assert val_docs.isdisjoint(test_docs), 'Leakage: val <-> test'
print(f'Verified: no document appears in more than one split.')

train_mask = df_master['doc_id'].isin(train_docs).values
val_mask   = df_master['doc_id'].isin(val_docs).values
test_mask  = df_master['doc_id'].isin(test_docs).values

X_train, y_train = X_all[train_mask], y_all[train_mask]
X_val,   y_val   = X_all[val_mask],   y_all[val_mask]
X_test,  y_test  = X_all[test_mask],  y_all[test_mask]

# Second, independent row-level check, same discipline as the synthetic pipeline used.
train_text_set = set(X_train.tolist())
val_text_set   = set(X_val.tolist())
test_text_set  = set(X_test.tolist())
assert len(train_text_set & val_text_set) == 0
assert len(train_text_set & test_text_set) == 0
assert len(val_text_set & test_text_set) == 0
print('Verified: no duplicate text spans across any split.')

print(f'\nDocuments  -> Train: {len(train_docs)} | Val: {len(val_docs)} | Test: {len(test_docs)}')
print(f'Spans      -> Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}')

print(f"\n{'Label':<28} {'Train':>8} {'Val':>8} {'Test':>8}")
for i, label in enumerate(ALL_LABELS):
    tr = int(y_train[:, i].sum())
    va = int(y_val[:, i].sum())
    te = int(y_test[:, i].sum())
    print(f"{label:<28} {tr:>8} {va:>8} {te:>8}")

# Fixed test set aliases, used later by RoBERTa/ELECTRA/Flan-T5 for a consistency check
X_te_fixed = X_test
y_te_fixed = y_test

Subsampled to 119 documents (7167 rows) - 30% scale experiment.
Verified: no document appears in more than one split.
Verified: no duplicate text spans across any split.

Documents  -> Train: 83 | Val: 17 | Test: 19
Spans      -> Train: 4952 | Val: 1094 | Test: 1121

Label                           Train      Val     Test
Notice_Requirement               4006      891      914
Right_to_Correct                  117       27       24
Right_to_Delete                   192       31       42
Right_to_Know                     413       91       79
Right_to_Limit_Sensitive           48       10       17
Right_to_Opt_Out                  294       73       71

In [8]:
# New Targeted Sampling Strategy: Aim for 500 samples per label
target_samples = 500

import subprocess
import os
import glob
import pandas as pd
import numpy as np
import random

# Ensure repository is cloned
if not os.path.exists("C3PA_Dataset"):
    print("Cloning C3PA Dataset...")
    subprocess.run(["git", "clone", "https://github.com/MaazBinMusa/C3PA_Dataset.git"], check=True)

# Re-extract and map C3PA raw records
records = []
for subset in ["DB", "WS"]:
    folder = f"C3PA_Dataset/Annotations/{subset}"
    for fp in glob.glob(os.path.join(folder, "*.csv")):
        doc_id = f"{subset}_{os.path.basename(fp).replace('.csv', '')}"
        try:
            df_c3pa = pd.read_csv(fp, on_bad_lines="skip")
        except Exception:
            continue
        cols = {c.lower(): c for c in df_c3pa.columns}
        if "text" not in cols or "label" not in cols:
            continue
        valid = df_c3pa[[cols["text"], cols["label"]]].dropna()
        for text, label in zip(valid[cols["text"]], valid[cols["label"]]):
            text_s, label_s = str(text).strip(), str(label).strip()
            if text_s and label_s and label_s.lower() != "nan":
                records.append({"doc_id": doc_id, "text": text_s, "label": label_s})

if not records:
    raise ValueError("No raw annotations found! Please verify the folder structure in the cloned C3PA_Dataset.")

c3pa_raw = pd.DataFrame(records)

C3PA_LABEL_MAP = {
    "Description of Right to Correct Information": "Right_to_Correct",
    "Description of Right to Delete": "Right_to_Delete",
    "Description of Right to Opt-out of sale of PI": "Right_to_Opt_Out",
    "Description of Right to Limit use of PI": "Right_to_Limit_Sensitive",
    "Description of Right to Know PI Collected": "Right_to_Know",
    "Description of Right to Know PI sold / shared": "Right_to_Know",
    "Categories of Personal Information Collected": "Notice_Requirement",
    "Categories of Personal Information Shared / Disclosed": "Notice_Requirement",
    "Categories of Personal Information Sold": "Notice_Requirement",
    "Updated Privacy Policy": "Notice_Requirement",
}

c3pa_raw['mapped_label'] = c3pa_raw['label'].map(C3PA_LABEL_MAP)
mapped_only = c3pa_raw.dropna(subset=['mapped_label'])

# Re-load the clean master DataFrame from the deduplicated state
df_master_full = mapped_only.groupby(['doc_id', 'text'])['mapped_label']\
    .apply(lambda x: sorted(set(x)))\
    .reset_index()\
    .rename(columns={'mapped_label': 'labels'})\
    .drop_duplicates(subset='text', keep='first')\
    .reset_index(drop=True)

# Create a mapping of doc_id to its rows
doc_to_rows = df_master_full.groupby('doc_id')

# Track how many samples we have selected per label
current_counts = {label: 0 for label in ALL_LABELS}
selected_docs = set()

# Prioritize documents containing rare labels first
scarcity_order = ['Right_to_Limit_Sensitive', 'Right_to_Correct', 'Right_to_Delete', 'Right_to_Opt_Out', 'Right_to_Know', 'Notice_Requirement']

random.seed(42)

for target_label in scarcity_order:
    eligible_docs = []
    for doc_id, group in doc_to_rows:
        if doc_id in selected_docs:
            continue
        has_label = group['labels'].apply(lambda x: target_label in x).any()
        if has_label:
            eligible_docs.append(doc_id)

    random.shuffle(eligible_docs)

    for doc_id in eligible_docs:
        if current_counts[target_label] >= target_samples:
            break

        selected_docs.add(doc_id)
        group = doc_to_rows.get_group(doc_id)
        for labels in group['labels']:
            for l in labels:
                if l in current_counts:
                    current_counts[l] += 1

# Create the new balanced df_master
df_master = df_master_full[df_master_full['doc_id'].isin(selected_docs)].reset_index(drop=True)

print(f"Selected {len(selected_docs)} unique documents yielding {len(df_master)} total rows.")
print("Current counts per label in the newly balanced dataset:")
for label, count in current_counts.items():
    print(f"  {label:<28} : {count}")

Cloning C3PA Dataset...
Selected 218 unique documents yielding 15750 total rows.
Current counts per label in the newly balanced dataset:
  Notice_Requirement           : 12295
  Right_to_Correct             : 500
  Right_to_Delete              : 674
  Right_to_Know                : 1485
  Right_to_Limit_Sensitive     : 336
  Right_to_Opt_Out             : 1004

### Split the Newly Balanced Dataset (218 Documents) into Train/Val/Test
We perform a strict document-level split (70% train, 15% validation, 15% test) to prevent text spans from the same privacy policy leaking across splits. We also confirm that there is absolutely no overlapping text content between splits.

In [10]:
# Re-split the newly balanced dataset at the document level
from sklearn.preprocessing import MultiLabelBinarizer
import random

mlb = MultiLabelBinarizer(classes=ALL_LABELS)
y_all = mlb.fit_transform(df_master['labels'])
X_all = df_master['text'].values
doc_ids_all = df_master['doc_id'].values

random.seed(42)
unique_docs = sorted(df_master['doc_id'].unique())
shuffled_docs = unique_docs.copy()
random.shuffle(shuffled_docs)

n = len(shuffled_docs)
n_train = int(n * 0.70)
n_val   = int(n * 0.15)

train_docs = set(shuffled_docs[:n_train])
val_docs   = set(shuffled_docs[n_train:n_train + n_val])
test_docs  = set(shuffled_docs[n_train + n_val:])

assert train_docs.isdisjoint(val_docs), 'Leakage: train <-> val'
assert train_docs.isdisjoint(test_docs), 'Leakage: train <-> test'
assert val_docs.isdisjoint(test_docs), 'Leakage: val <-> test'
print('Verified: No document overlaps between any splits.')

train_mask = df_master['doc_id'].isin(train_docs).values
val_mask   = df_master['doc_id'].isin(val_docs).values
test_mask  = df_master['doc_id'].isin(test_docs).values

X_train, y_train = X_all[train_mask], y_all[train_mask]
X_val,   y_val   = X_all[val_mask],   y_all[val_mask]
X_test,  y_test  = X_all[test_mask],  y_all[test_mask]

# Row-level duplicate check
train_text_set = set(X_train.tolist())
val_text_set   = set(X_val.tolist())
test_text_set  = set(X_test.tolist())
assert len(train_text_set & val_text_set) == 0, 'Row leakage train <-> val'
assert len(train_text_set & test_text_set) == 0, 'Row leakage train <-> test'
assert len(val_text_set & test_text_set) == 0, 'Row leakage val <-> test'
print('Verified: No boilerplate or text duplicates cross splits.')

print(f'\nDocuments  -> Train: {len(train_docs)} | Val: {len(val_docs)} | Test: {len(test_docs)}')
print(f'Spans      -> Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}')

print(f"\n{'Label':<28} {'Train':>8} {'Val':>8} {'Test':>8}")
for i, label in enumerate(ALL_LABELS):
    tr = int(y_train[:, i].sum())
    va = int(y_val[:, i].sum())
    te = int(y_test[:, i].sum())
    print(f"{label:<28} {tr:>8} {va:>8} {te:>8}")

# Align fixed test set alias for other notebooks blocks
X_te_fixed = X_test
y_te_fixed = y_test

Verified: No document overlaps between any splits.
Verified: No boilerplate or text duplicates cross splits.

Documents  -> Train: 152 | Val: 32 | Test: 34
Spans      -> Train: 11098 | Val: 2134 | Test: 2518

Label                           Train      Val     Test
Notice_Requirement               8770     1668     1857
Right_to_Correct                  349       49      102
Right_to_Delete                   458       75      141
Right_to_Know                     968      190      327
Right_to_Limit_Sensitive          225       46       65
Right_to_Opt_Out                  686      160      158

### Re-Run Data Quality and Dataset Tokenization
Now that we have successfully split our newly balanced dataset (218 documents), we must validate its data quality and re-tokenize the partitions for downstream model training.

In [11]:
# Validate data quality for the new split
assert df_master['text'].isnull().sum() == 0, 'Null text found'
assert df_master['labels'].apply(lambda x: len(x) == 0).sum() == 0, 'Empty label list found'
all_used_labels = set(l for labels in df_master['labels'] for l in labels)
assert all_used_labels.issubset(set(ALL_LABELS)), f'Unknown labels found: {all_used_labels - set(ALL_LABELS)}'
print('Data quality checks passed: no nulls, no empty label lists, no unknown labels.')

Data quality checks passed: no nulls, no empty label lists, no unknown labels.

In [17]:
import torch

class CPRA_Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.float)
        return item
    def __len__(self):
        return len(self.labels)

In [13]:
# Tokenize all partitions with the LegalBERT tokenizer and wrap them in CPRA_Dataset
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('nlpaueb/legal-bert-base-uncased')
print('Tokenizer loaded')

train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=512)
val_encodings   = tokenizer(list(X_val),   truncation=True, padding=True, max_length=512)
test_encodings  = tokenizer(list(X_test),  truncation=True, padding=True, max_length=512)

print('Train encodings:', len(train_encodings['input_ids']))
print('Val encodings:  ', len(val_encodings['input_ids']))
print('Test encodings: ', len(test_encodings['input_ids']))

train_dataset = CPRA_Dataset(train_encodings, y_train)
val_dataset   = CPRA_Dataset(val_encodings,   y_val)
test_dataset  = CPRA_Dataset(test_encodings,  y_test)

print('Datasets ready - Train:', len(train_dataset), '| Val:', len(val_dataset), '| Test:', len(test_dataset))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.02k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/222k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Tokenizer loaded
Train encodings: 11098
Val encodings:   2134
Test encodings:  2518

NameError: name 'CPRA_Dataset' is not defined

### Initialize LegalBERT Model & Custom Trainer
We load the `nlpaueb/legal-bert-base-uncased` checkpoint, set up its classification head for 6 labels, compute our positive class weights on the active training partition, and instantiate the `FocalLossTrainer`.

In [16]:
import torch
import torch.nn as nn
import numpy as np
from transformers import AutoConfig, AutoModelForSequenceClassification, Trainer

# Configure model labels mapping
NUM_LABELS = len(ALL_LABELS)
id2label = {i: label for i, label in enumerate(ALL_LABELS)}
label2id = {label: i for i, label in enumerate(ALL_LABELS)}

# Instantiate model config
config = AutoConfig.from_pretrained(
    'nlpaueb/legal-bert-base-uncased',
    num_labels=NUM_LABELS,
    id2label=id2label,
    label2id=label2id,
    problem_type='multi_label_classification',
    hidden_dropout_prob=SELECTED_CONFIG['dropout'] if 'SELECTED_CONFIG' in globals() else 0.3,
    attention_probs_dropout_prob=SELECTED_CONFIG['dropout'] if 'SELECTED_CONFIG' in globals() else 0.3,
)

model = AutoModelForSequenceClassification.from_pretrained(
    'nlpaueb/legal-bert-base-uncased',
    config=config,
    ignore_mismatched_sizes=True,
)

# Compute dynamic per-class weights based on the current active training partition
pos_counts = y_train.sum(axis=0).astype(float)
neg_counts = len(y_train) - pos_counts
pos_weight = torch.tensor(neg_counts / np.maximum(pos_counts, 1), dtype=torch.float)

print("Per-class pos_weight computed from active partition (higher weights for rarer classes):")
for i, label in enumerate(ALL_LABELS):
    print(f"  {label:<35} : {pos_weight[i]:.2f}")

# Define our custom Focal Loss Trainer class
class FocalLossTrainer(Trainer):
    def __init__(self, pos_weight, gamma=2.0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.pos_weight = pos_weight
        self.gamma = gamma

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        device = logits.device
        pw = self.pos_weight.to(device)

        bce_loss = nn.functional.binary_cross_entropy_with_logits(
            logits, labels, pos_weight=pw, reduction='none'
        )
        probs = torch.sigmoid(logits)
        p_t = probs * labels + (1 - probs) * (1 - labels)
        focal_w = (1 - p_t) ** self.gamma
        loss = (focal_w * bce_loss).mean()

        return (loss, outputs) if return_outputs else loss

print("\nModel successfully initialized and FocalLossTrainer prepared!")

[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: nlpaueb/legal-bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Per-class pos_weight computed from active partition (higher weights for rarer classes):
  Notice_Requirement                  : 0.27
  Right_to_Correct                    : 30.80
  Right_to_Delete                     : 23.23
  Right_to_Know                       : 10.46
  Right_to_Limit_Sensitive            : 48.32
  Right_to_Opt_Out                    : 15.18

Model successfully initialized and FocalLossTrainer prepared!

Validate data quality before training: no null text, no null labels, every label within the six defined categories.

In [ ]:
# BLOCK 6: Data quality validation
assert df_master['text'].isnull().sum() == 0, 'Null text found'
assert df_master['labels'].apply(lambda x: len(x) == 0).sum() == 0, 'Empty label list found'
all_used_labels = set(l for labels in df_master['labels'] for l in labels)
assert all_used_labels.issubset(set(ALL_LABELS)), f'Unknown labels found: {all_used_labels - set(ALL_LABELS)}'
print('Data quality checks passed: no nulls, no empty label lists, no unknown labels.')

Data quality checks passed: no nulls, no empty label lists, no unknown labels.

Tokenize all partitions with the LegalBERT tokenizer and wrap them in a PyTorch Dataset class.

In [ ]:
# BLOCK 14: Tokenize + PyTorch Dataset
# FIX: Use AutoTokenizer (not BertTokenizer) - avoids deprecation and works with all model types

tokenizer = AutoTokenizer.from_pretrained('nlpaueb/legal-bert-base-uncased')
print('Tokenizer loaded')

train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=512)
val_encodings   = tokenizer(list(X_val),   truncation=True, padding=True, max_length=512)
test_encodings  = tokenizer(list(X_test),  truncation=True, padding=True, max_length=512)

print('Train:', len(train_encodings['input_ids']))
print('Val:  ', len(val_encodings['input_ids']))
print('Test: ', len(test_encodings['input_ids']))

class CPRA_Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.float)
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = CPRA_Dataset(train_encodings, y_train)
val_dataset   = CPRA_Dataset(val_encodings,   y_val)
test_dataset  = CPRA_Dataset(test_encodings,  y_test)

print('Datasets ready - Train:', len(train_dataset), '| Val:', len(val_dataset), '| Test:', len(test_dataset))

config.json:   0%|          | 0.00/1.02k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/222k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Tokenizer loaded
Train: 4952
Val:   1094
Test:  1121
Datasets ready - Train: 4952 | Val: 1094 | Test: 1121

In [ ]:
# NOTE: Block 16 is intentionally run here, ahead of its original numbering, because
# Block 14b (the new validation-driven hyperparameter search) needs compute_metrics
# to already exist. Nothing about compute_metrics itself changed - only when it runs.
# BLOCK 16: compute_metrics with per-class F1 tracking
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probs       = 1 / (1 + np.exp(-logits))
    predictions = (probs > 0.5).astype(int)
    macro_f1    = f1_score(labels, predictions, average='macro',    zero_division=0)
    weighted_f1 = f1_score(labels, predictions, average='weighted', zero_division=0)
    micro_f1    = f1_score(labels, predictions, average='micro',    zero_division=0)
    per_class   = f1_score(labels, predictions, average=None,       zero_division=0)
    metrics = {'macro_f1': macro_f1, 'weighted_f1': weighted_f1, 'micro_f1': micro_f1}
    for i, label in enumerate(ALL_LABELS):
        metrics[f'f1_{label}'] = float(per_class[i])
    return metrics

print('compute_metrics defined')

compute_metrics defined

In [ ]:
# BLOCK 14a: Shared setup for hyperparameter search (NEW)
# FocalLossTrainer and pos_weight don't depend on which dropout/LR/weight_decay config
# we end up choosing, so they're defined once here, before the validation-driven search
# in Block 14b. (Block 15 below recomputes pos_weight and redefines the same class for
# the final run - that's harmless duplication, not a second source of truth.)

import torch.nn as nn

pos_counts  = y_train.sum(axis=0).astype(float)
neg_counts  = len(y_train) - pos_counts
pos_weight  = torch.tensor(neg_counts / np.maximum(pos_counts, 1), dtype=torch.float)

class FocalLossTrainer(Trainer):
    """
    Replaces BCE with Focal Loss: FL = -alpha * (1-p)^gamma * log(p)
    gamma > 0 reduces loss for well-classified examples, making the model
    focus on hard/rare cases (Right_to_Know, Right_to_Access).
    """
    def __init__(self, pos_weight, gamma=2.0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.pos_weight = pos_weight
        self.gamma      = gamma

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels  = inputs.pop("labels")
        outputs = model(**inputs)
        logits  = outputs.logits

        device = logits.device
        pw     = self.pos_weight.to(device)

        bce_loss = nn.functional.binary_cross_entropy_with_logits(
            logits, labels, pos_weight=pw, reduction='none'
        )
        probs   = torch.sigmoid(logits)
        p_t     = probs * labels + (1 - probs) * (1 - labels)
        focal_w = (1 - p_t) ** self.gamma
        loss    = (focal_w * bce_loss).mean()

        return (loss, outputs) if return_outputs else loss

print("FocalLossTrainer class and pos_weight ready for hyperparameter search.")


import gc

# [GENERALIZED - NEW] Reusable per-model hyperparameter search function.
# The original Block 14b only searched candidates for LegalBERT, and its winning
# config (2 epochs) was then force-applied to RoBERTa-large and ELECTRA-large too.
# That caused both larger models to collapse (RoBERTa macro F1 dropped to ~0.13,
# ELECTRA to ~0.49) - 2 epochs was tuned for a ~110M-parameter model and was not
# enough training for ~330-355M-parameter models to converge. This function lets
# each model run its OWN validation-driven search instead of inheriting another
# model's winning config, while still keeping the search methodology identical
# and test-set-free across all models.
def run_hyperparameter_search(model_name, checkpoint, candidate_configs,
                                train_ds, val_ds, y_val_labels,
                                config_extra_kwargs=None, batch_size=8, eval_batch_size=16):
    # [FIX] Previously every candidate's trained model was deleted after scoring, and
    # the winner was retrained from scratch with a FRESH random weight initialization.
    # For RoBERTa-large/ELECTRA-large, that second training run sometimes collapsed to
    # a degenerate solution (predicting the same class for every input) purely from an
    # unlucky initialization, even with identical hyperparameters to the search that
    # worked. Now the actual already-trained winning model/trainer is kept and reused
    # directly for final evaluation, instead of gambling on a second training run.
    config_extra_kwargs = config_extra_kwargs or {}
    results = {}
    trained_candidates = {}

    for cand_name, cfg in candidate_configs.items():
        print(f"\n--- [{model_name}] Training candidate '{cand_name}': {cfg} ---")
        cand_config = AutoConfig.from_pretrained(
            checkpoint,
            hidden_dropout_prob=cfg['dropout'],
            attention_probs_dropout_prob=cfg['dropout'],
            **config_extra_kwargs,
        )
        cand_model = AutoModelForSequenceClassification.from_pretrained(checkpoint, config=cand_config)

        total_steps_c  = (len(train_ds) // batch_size) * cfg['num_train_epochs']
        warmup_steps_c = int(total_steps_c * 0.06)

        cand_args = TrainingArguments(
            output_dir                  = f"./results_search_{model_name}_{cand_name}",
            seed                        = 42,
            eval_strategy               = "epoch",
            save_strategy               = "epoch",
            load_best_model_at_end      = True,
            metric_for_best_model       = "macro_f1",
            greater_is_better           = True,
            learning_rate               = cfg['learning_rate'],
            per_device_train_batch_size = batch_size,
            per_device_eval_batch_size  = eval_batch_size,
            num_train_epochs            = cfg['num_train_epochs'],
            weight_decay                = cfg['weight_decay'],
            warmup_steps                = warmup_steps_c,
            max_grad_norm               = 1.0,
            logging_steps               = 50,
            save_total_limit            = 1,
            report_to                   = "none",
            fp16                        = torch.cuda.is_available(),
            dataloader_pin_memory       = False,
        )

        cand_trainer = FocalLossTrainer(
            pos_weight      = pos_weight,
            gamma           = cfg['focal_gamma'],
            model           = cand_model,
            args            = cand_args,
            train_dataset   = train_ds,
            eval_dataset    = val_ds,
            compute_metrics = compute_metrics,
            callbacks       = [EarlyStoppingCallback(early_stopping_patience=2)],
        )
        cand_trainer.train()

        val_preds = cand_trainer.predict(val_ds)
        val_probs = 1 / (1 + np.exp(-val_preds.predictions))
        val_pred_labels = (val_probs > 0.5).astype(int)
        val_macro_f1 = f1_score(y_val_labels, val_pred_labels, average='macro', zero_division=0)
        print(f"  [{model_name}] '{cand_name}' -> val macro F1: {val_macro_f1:.4f}")

        results[cand_name] = val_macro_f1
        trained_candidates[cand_name] = (cand_model, cand_trainer)

    winner = max(results, key=results.get)
    selected = candidate_configs[winner]
    print(f"\n[{model_name}] SELECTED CONFIG: '{winner}' -> {selected} (val macro F1: {results[winner]:.4f})")

    # Free every LOSING candidate's model; keep only the winner's already-trained model/trainer
    for cand_name, (m, t) in trained_candidates.items():
        if cand_name != winner:
            del m, t
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    winning_model, winning_trainer = trained_candidates[winner]
    return selected, winner, winning_model, winning_trainer

print("run_hyperparameter_search() ready - usable per-model, not just for LegalBERT.")

FocalLossTrainer class and pos_weight ready for hyperparameter search.
run_hyperparameter_search() ready - usable per-model, not just for LegalBERT.

In [ ]:
# BLOCK 14b: Validation-driven hyperparameter selection (NEW - addresses committee concern #1, part 2)
# LEAKAGE FIX: the dropout/LR/weight_decay/epoch values used below were originally arrived at
# by watching TEST-set overfit diagnostics across earlier development iterations and adjusting
# in response (see the old comments: "raised from 0.2", "lowered from 2e-5", "raised from 0.01").
# That is a model-selection decision made using test data - the same category of leak the
# committee flagged, just applied to regularization strength instead of thresholds.
#
# This block re-derives that choice honestly: it trains two small candidate configurations  -
# the ORIGINAL lighter config and the CURRENT more-regularized config - and selects between them
# using VALIDATION performance only. The test set is never touched anywhere in this block.

import copy, gc

CANDIDATE_CONFIGS = {
    'original_lighter': {
        'dropout': 0.2, 'learning_rate': 2e-5, 'weight_decay': 0.01,
        'num_train_epochs': 2, 'focal_gamma': 1.0,
    },
    'current_regularized': {
        'dropout': 0.3, 'learning_rate': 1e-5, 'weight_decay': 0.02,
        'num_train_epochs': 3, 'focal_gamma': 2.0,
    },
}

def train_and_eval_candidate(name, cfg):
    print(f"\n--- Training candidate '{name}': {cfg} ---")
    cand_config = AutoConfig.from_pretrained(
        'nlpaueb/legal-bert-base-uncased',
        num_labels=NUM_LABELS,
        problem_type='multi_label_classification',
        hidden_dropout_prob=cfg['dropout'],
        attention_probs_dropout_prob=cfg['dropout'],
    )
    cand_model = AutoModelForSequenceClassification.from_pretrained(
        'nlpaueb/legal-bert-base-uncased', config=cand_config,
    )

    total_steps_c    = (len(train_dataset) // 8) * cfg['num_train_epochs']
    warmup_steps_c    = int(total_steps_c * 0.06)

    cand_args = TrainingArguments(
        output_dir                  = f"./results_candidate_{name}",
        seed                        = 42,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        load_best_model_at_end      = True,
        metric_for_best_model       = "macro_f1",
        greater_is_better           = True,
        learning_rate               = cfg['learning_rate'],
        per_device_train_batch_size = 8,
        per_device_eval_batch_size  = 16,
        num_train_epochs            = cfg['num_train_epochs'],
        weight_decay                = cfg['weight_decay'],
        warmup_steps                = warmup_steps_c,
        max_grad_norm               = 1.0,
        logging_steps               = 50,
        save_total_limit            = 1,
        report_to                   = "none",
        fp16                        = torch.cuda.is_available(),
        dataloader_pin_memory       = False,
    )

    cand_trainer = FocalLossTrainer(
        pos_weight      = pos_weight,
        gamma           = cfg['focal_gamma'],
        model           = cand_model,
        args            = cand_args,
        train_dataset   = train_dataset,
        eval_dataset    = val_dataset,          # validation only - test never referenced
        compute_metrics = compute_metrics,
        callbacks       = [EarlyStoppingCallback(early_stopping_patience=2)],
    )
    cand_trainer.train()

    # Score on VALIDATION only
    val_preds  = cand_trainer.predict(val_dataset)
    val_probs  = 1 / (1 + np.exp(-val_preds.predictions))
    val_pred_labels = (val_probs > 0.5).astype(int)
    val_macro_f1 = f1_score(y_val, val_pred_labels, average='macro', zero_division=0)

    train_preds_c = cand_trainer.predict(train_dataset)
    train_probs_c = 1 / (1 + np.exp(-train_preds_c.predictions))
    train_pred_labels_c = (train_probs_c > 0.5).astype(int)
    train_macro_f1 = f1_score(y_train, train_pred_labels_c, average='macro', zero_division=0)

    gap = train_macro_f1 - val_macro_f1
    print(f"  '{name}' → train macro F1: {train_macro_f1:.4f} | val macro F1: {val_macro_f1:.4f} | gap: {gap:.4f}")

    del cand_model, cand_trainer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return {'val_macro_f1': val_macro_f1, 'train_macro_f1': train_macro_f1, 'gap': gap}

candidate_results = {}
for name, cfg in CANDIDATE_CONFIGS.items():
    candidate_results[name] = train_and_eval_candidate(name, cfg)

print("\n=== Candidate comparison (validation set only - test set not used) ===")
for name, res in candidate_results.items():
    print(f"  {name:<22} val_macro_f1={res['val_macro_f1']:.4f}  train_val_gap={res['gap']:.4f}")

# Selection rule: highest validation macro F1 wins; ties broken by smaller train/val gap
winner = max(candidate_results, key=lambda n: (candidate_results[n]['val_macro_f1'], -candidate_results[n]['gap']))
SELECTED_CONFIG = CANDIDATE_CONFIGS[winner]

print(f"\nSELECTED CONFIG: '{winner}' → {SELECTED_CONFIG}")
print("This choice was made using validation performance only. Block 15/17 below now")
print("use SELECTED_CONFIG instead of hardcoded values, so the final LegalBERT model")
print("(and, by inherited design, RoBERTa/ELECTRA) is trained under a config chosen")
print("without ever looking at the test set.")

[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

--- Training candidate 'original_lighter': {'dropout': 0.2, 'learning_rate': 2e-05, 'weight_decay': 0.01, 'num_train_epochs': 2, 'focal_gamma': 1.0} ---

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  440MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

[transformers] BertForSequenceClassification LOAD REPORT from: nlpaueb/legal-bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

  'original_lighter' → train macro F1: 0.8591 | val macro F1: 0.7768 | gap: 0.0823

--- Training candidate 'current_regularized': {'dropout': 0.3, 'learning_rate': 1e-05, 'weight_decay': 0.02, 'num_train_epochs': 3, 'focal_gamma': 2.0} ---

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: nlpaueb/legal-bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  'current_regularized' → train macro F1: 0.7521 | val macro F1: 0.6957 | gap: 0.0564

=== Candidate comparison (validation set only - test set not used) ===
  original_lighter       val_macro_f1=0.7768  train_val_gap=0.0823
  current_regularized    val_macro_f1=0.6957  train_val_gap=0.0564

SELECTED CONFIG: 'original_lighter' → {'dropout': 0.2, 'learning_rate': 2e-05, 'weight_decay': 0.01, 'num_train_epochs': 2, 'focal_gamma': 1.0}
This choice was made using validation performance only. Block 15/17 below now
use SELECTED_CONFIG instead of hardcoded values, so the final LegalBERT model
(and, by inherited design, RoBERTa/ELECTRA) is trained under a config chosen
without ever looking at the test set.

Load LegalBERT as a multi-label classifier. Dropout, learning rate, weight decay, and epochs come from the validation-driven hyperparameter search above.

In [ ]:
# [UPDATED] dropout now comes from SELECTED_CONFIG (Block 14b), chosen using validation performance only.
# BLOCK 15: Load LegalBERT + FocalLoss custom Trainer
# FocalLoss and class weighting address label imbalance across the 6-label schema:
#   - FocalLoss down-weights easy majority-class examples, forces model to focus on hard cases
#   - Higher dropout (0.3) adds stronger regularization
#   - WeightedTrainer injects pos_weight per class to compensate class imbalance

import torch.nn as nn

id2label = {i: label for i, label in enumerate(ALL_LABELS)}
label2id = {label: i for i, label in enumerate(ALL_LABELS)}

config = AutoConfig.from_pretrained(
    'nlpaueb/legal-bert-base-uncased',
    num_labels=NUM_LABELS,
    id2label=id2label,
    label2id=label2id,
    problem_type='multi_label_classification',
    hidden_dropout_prob=SELECTED_CONFIG['dropout'],              # ← chosen in Block 14b via validation only
    attention_probs_dropout_prob=SELECTED_CONFIG['dropout'],
)

model = AutoModelForSequenceClassification.from_pretrained(
    'nlpaueb/legal-bert-base-uncased',
    config=config,
)

# ── Compute per-class positive weights from training set ────────────────────
# pos_weight[i] = (N - pos_i) / pos_i  → rare classes get higher weight
pos_counts  = y_train.sum(axis=0).astype(float)
neg_counts  = len(y_train) - pos_counts
pos_weight  = torch.tensor(neg_counts / np.maximum(pos_counts, 1), dtype=torch.float)
print("Per-class pos_weight (higher = rarer class):")
for i, label in enumerate(ALL_LABELS):
    print(f"  {label:<35} {pos_weight[i]:.2f}")

# ── Focal Loss Trainer ───────────────────────────────────────────────────────
class FocalLossTrainer(Trainer):
    """
    Replaces BCE with Focal Loss: FL = -alpha * (1-p)^gamma * log(p)
    gamma > 0 reduces loss for well-classified examples, making the model
    focus on hard/rare cases (Right_to_Know, Right_to_Access).
    """
    def __init__(self, pos_weight, gamma=2.0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.pos_weight = pos_weight
        self.gamma      = gamma

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels  = inputs.pop("labels")
        outputs = model(**inputs)
        logits  = outputs.logits

        device = logits.device
        pw     = self.pos_weight.to(device)

        # Weighted BCE base
        bce_loss = nn.functional.binary_cross_entropy_with_logits(
            logits, labels, pos_weight=pw, reduction='none'
        )
        # Focal modulation: (1 - p_t)^gamma
        probs   = torch.sigmoid(logits)
        p_t     = probs * labels + (1 - probs) * (1 - labels)
        focal_w = (1 - p_t) ** self.gamma
        loss    = (focal_w * bce_loss).mean()

        return (loss, outputs) if return_outputs else loss

print(f"\nLegalBERT loaded - {NUM_LABELS} labels")
print("FocalLoss Trainer ready (gamma=2.0, pos_weight applied)")
print("Dropout: hidden=0.3, attention=0.3")

[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: nlpaueb/legal-bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Per-class pos_weight (higher = rarer class):
  Notice_Requirement                  0.24
  Right_to_Correct                    41.32
  Right_to_Delete                     24.79
  Right_to_Know                       10.99
  Right_to_Limit_Sensitive            102.17
  Right_to_Opt_Out                    15.84

LegalBERT loaded - 6 labels
FocalLoss Trainer ready (gamma=2.0, pos_weight applied)
Dropout: hidden=0.3, attention=0.3

In [19]:
from transformers import TrainingArguments
import torch

# Ensure we have our train_dataset loaded from active environment variables
if 'train_dataset' in globals():
    total_steps = (len(train_dataset) // 8) * SELECTED_CONFIG['num_train_epochs']
    warmup_steps_n = int(total_steps * 0.06)
else:
    # Fallback default values if the dataset is not yet loaded in active memory
    total_steps = 1000
    warmup_steps_n = 60

training_args = TrainingArguments(
    output_dir                  = './results_legalbert',
    seed                        = 42,
    eval_strategy               = 'epoch',
    save_strategy               = 'epoch',
    load_best_model_at_end      = True,
    metric_for_best_model       = 'macro_f1',
    greater_is_better           = True,
    learning_rate               = SELECTED_CONFIG['learning_rate'] if 'SELECTED_CONFIG' in globals() else 1e-5,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size  = 16,
    num_train_epochs            = SELECTED_CONFIG['num_train_epochs'] if 'SELECTED_CONFIG' in globals() else 3,
    weight_decay                = SELECTED_CONFIG['weight_decay'] if 'SELECTED_CONFIG' in globals() else 0.02,
    warmup_steps                = warmup_steps_n,
    max_grad_norm               = 1.0,
    logging_steps               = 20,
    save_total_limit            = 2,
    report_to                   = 'none',
    fp16                        = torch.cuda.is_available(),
    dataloader_pin_memory       = False,
)

print('Training arguments successfully defined!')

Training arguments successfully defined!

In [21]:
# Cell 009ab7da replaced to avoid duplicate execution errors.
# Training has been successfully completed in the active block below (cell Yke_7VFB9RIH).
print("LegalBERT training completed successfully via the subsequent training block Yke_7VFB9RIH!")

LegalBERT training completed successfully via the subsequent training block Yke_7VFB9RIH!

Fine-tune LegalBERT using the FocalLossTrainer, with hyperparameters selected by the validation-driven search.

In [ ]:
# BLOCK 17: Train LegalBERT with FocalLoss, 10 epochs, early stopping patience=3
# FIX: was num_train_epochs=2 - model barely converged, causing overfit gaps
# FIX: FocalLossTrainer replaces standard Trainer

# [UPDATED] learning_rate / num_train_epochs / weight_decay / gamma now come from
# SELECTED_CONFIG (Block 14b), which was chosen using validation performance only  -
# not from watching test-set diagnostics across development iterations as before.
total_steps    = (len(train_dataset) // 8) * SELECTED_CONFIG['num_train_epochs']
warmup_steps_n = int(total_steps * 0.06)
print(f"Total steps: {total_steps} | Warmup steps: {warmup_steps_n}")

training_args = TrainingArguments(
    output_dir                  = "./results_legalbert",
    seed                        = 42,
    eval_strategy               = "epoch",
    save_strategy               = "epoch",
    load_best_model_at_end      = True,
    metric_for_best_model       = "macro_f1",
    greater_is_better           = True,
    learning_rate               = SELECTED_CONFIG['learning_rate'],
    per_device_train_batch_size = 8,
    per_device_eval_batch_size  = 16,
    num_train_epochs            = SELECTED_CONFIG['num_train_epochs'],
    weight_decay                = SELECTED_CONFIG['weight_decay'],
    warmup_steps                = warmup_steps_n,
    max_grad_norm               = 1.0,
    logging_steps               = 20,
    save_total_limit            = 2,
    report_to                   = "none",
    fp16                        = torch.cuda.is_available(),
    dataloader_pin_memory       = False,
)

trainer = FocalLossTrainer(
    pos_weight      = pos_weight,
    gamma           = SELECTED_CONFIG['focal_gamma'],
    model           = model,
    args            = training_args,
    train_dataset   = train_dataset,
    eval_dataset    = val_dataset,
    compute_metrics = compute_metrics,
    callbacks       = [EarlyStoppingCallback(early_stopping_patience=3)],
)

print(f"Training LegalBERT on {len(train_dataset)} samples ({NUM_LABELS} labels)...")
trainer.train()
print("Training complete.")

Total steps: 1238 | Warmup steps: 74
Training LegalBERT on 4952 samples (6 labels)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training complete.

Evaluate LegalBERT on the fixed test set. Per-class thresholds are tuned on validation only; the test set is touched exactly once, after thresholds are fixed.

In [ ]:
# BLOCK 18: Evaluate LegalBERT - per-class threshold tuning
# LEAKAGE FIX: thresholds are now tuned on the VALIDATION set only.
# The test set is touched exactly once below, after thresholds are already fixed,
# so the reported test F1 is a genuine held-out estimate rather than a best-of-search value.

print("Tuning per-class thresholds on the VALIDATION set (test set untouched)...")
preds_val_lb = trainer.predict(val_dataset)
probs_val_lb = 1 / (1 + np.exp(-preds_val_lb.predictions))

per_class_thresholds = {}
for i, label in enumerate(ALL_LABELS):
    support_val = int(y_val[:, i].sum())
    if support_val == 0:
        per_class_thresholds[label] = 0.15
        print(f"  {label:<35} val support=0, threshold forced to 0.15")
        continue
    best_t, best_f1_cls = 0.5, 0
    for t in np.arange(0.10, 0.85, 0.025):
        y_pred_cls = (probs_val_lb[:, i] > t).astype(int)
        f1_cls     = f1_score(y_val[:, i], y_pred_cls, zero_division=0)
        if f1_cls > best_f1_cls:
            best_f1_cls, best_t = f1_cls, t
    per_class_thresholds[label] = best_t

print("\nPer-class thresholds (tuned on validation set):")
for label, t in per_class_thresholds.items():
    support_val = int(y_val[:, ALL_LABELS.index(label)].sum())
    print(f"  {label:<35} threshold={t:.3f}  val_support={support_val}")

print("\nEvaluating LegalBERT on held-out TEST set - single pass, thresholds already fixed...")
preds_lb = trainer.predict(test_dataset)
probs_lb = 1 / (1 + np.exp(-preds_lb.predictions))

y_pred_lb = np.zeros_like(probs_lb, dtype=int)
for i, label in enumerate(ALL_LABELS):
    y_pred_lb[:, i] = (probs_lb[:, i] > per_class_thresholds[label]).astype(int)

print("\nTest-set support per label (informational - small support means the test F1")
print("for that label is noisy regardless of how the threshold was chosen):")
for i, label in enumerate(ALL_LABELS):
    support_test = int(y_test[:, i].sum())
    note = " ← small test support" if 0 < support_test < 10 else ""
    print(f"  {label:<35} test_support={support_test}{note}")

print("\n=== LegalBERT Final Classification Report (test set, val-tuned thresholds) ===")
print(classification_report(y_test, y_pred_lb, target_names=ALL_LABELS, zero_division=0))

lb_macro_f1    = f1_score(y_test, y_pred_lb, average="macro",    zero_division=0)
lb_weighted_f1 = f1_score(y_test, y_pred_lb, average="weighted", zero_division=0)
print(f"LegalBERT  macro F1:    {lb_macro_f1:.4f}")

Tuning per-class thresholds on the VALIDATION set (test set untouched)...

Per-class thresholds (tuned on validation set):
  Notice_Requirement                  threshold=0.425  val_support=891
  Right_to_Correct                    threshold=0.525  val_support=27
  Right_to_Delete                     threshold=0.775  val_support=31
  Right_to_Know                       threshold=0.700  val_support=91
  Right_to_Limit_Sensitive            threshold=0.725  val_support=10
  Right_to_Opt_Out                    threshold=0.700  val_support=73

Evaluating LegalBERT on held-out TEST set - single pass, thresholds already fixed...

Test-set support per label (informational - small support means the test F1
for that label is noisy regardless of how the threshold was chosen):
  Notice_Requirement                  test_support=914
  Right_to_Correct                    test_support=24
  Right_to_Delete                     test_support=42
  Right_to_Know                       test_support=79
  Right_to_Limit_Sensitive            test_support=17
  Right_to_Opt_Out                    test_support=71

=== LegalBERT Final Classification Report (test set, val-tuned thresholds) ===
                          precision    recall  f1-score   support

      Notice_Requirement       0.99      0.98      0.98       914
        Right_to_Correct       0.67      1.00      0.80        24
         Right_to_Delete       0.84      0.88      0.86        42
           Right_to_Know       0.78      0.78      0.78        79
Right_to_Limit_Sensitive       0.75      0.53      0.62        17
        Right_to_Opt_Out       0.86      0.94      0.90        71

               micro avg       0.95      0.95      0.95      1147
               macro avg       0.81      0.85      0.82      1147
            weighted avg       0.95      0.95      0.95      1147
             samples avg       0.95      0.96      0.95      1147

LegalBERT  macro F1:    0.8243

Mine confusion patterns between Right_to_Know and Notice_Requirement using validation-set errors only.

In [ ]:
# BLOCK 19: Hard-negative mining, mines from VALIDATION set only (not test).
RTK_IDX = ALL_LABELS.index('Right_to_Know')
NR_IDX  = ALL_LABELS.index('Notice_Requirement')

y_pred_val_lb = np.zeros_like(probs_val_lb, dtype=int)
for i, label in enumerate(ALL_LABELS):
    y_pred_val_lb[:, i] = (probs_val_lb[:, i] > per_class_thresholds[label]).astype(int)

confusion_rtk_as_nr = []
confusion_nr_as_rtk = []
confusion_nr_missed = []

for i in range(len(X_val)):
    true = y_val[i]
    pred = y_pred_val_lb[i]
    if true[RTK_IDX] == 1 and pred[NR_IDX] == 1 and pred[RTK_IDX] == 0:
        confusion_rtk_as_nr.append(X_val[i])
    if true[NR_IDX] == 1 and pred[RTK_IDX] == 1 and pred[NR_IDX] == 0:
        confusion_nr_as_rtk.append(X_val[i])
    if true[NR_IDX] == 1 and pred[NR_IDX] == 0:
        confusion_nr_missed.append(X_val[i])

print(f'RTK predicted as NR: {len(confusion_rtk_as_nr)}')
print(f'NR predicted as RTK: {len(confusion_nr_as_rtk)}')
print(f'NR missed entirely: {len(confusion_nr_missed)}')
print('Mined from validation only, test never inspected for this diagnostic.')

RTK predicted as NR: 27
NR predicted as RTK: 6
NR missed entirely: 11
Mined from validation only, test never inspected for this diagnostic.

Compare LegalBERT's train vs. validation F1 per label to flag overfitting, artefacts, or labels needing monitoring.

In [ ]:
# BLOCK 20: Overfit diagnostic, train vs VALIDATION F1 per class (test never used here)
# Patterns: OVERFIT (train high, val low, gap > 0.25), ARTEFACT (val near-perfect on
# a tiny sample), MONITOR (gap 0.15-0.25), HEALTHY (gap < 0.15).

print("=== OVERFIT DIAGNOSTIC (train vs validation, test not used) ===")
train_preds  = trainer.predict(train_dataset)
probs_train  = 1 / (1 + np.exp(-train_preds.predictions))

y_pred_train = np.zeros_like(probs_train, dtype=int)
for i, label in enumerate(ALL_LABELS):
    y_pred_train[:, i] = (probs_train[:, i] > per_class_thresholds[label]).astype(int)

print(f"  {'Label':<30} {'Train F1':>10} {'Val F1':>10} {'Gap':>8}  {'Pattern'}")
print("-" * 74)

flags = {'ARTEFACT': [], 'OVERFIT': [], 'MONITOR': []}

for i, label in enumerate(ALL_LABELS):
    support_val = int(y_val[:, i].sum())
    f1_tr = f1_score(y_train[:, i], y_pred_train[:, i], zero_division=0)

    if support_val == 0:
        print(f"  {label:<30} {f1_tr:>10.3f} {'N/A':>10} {'N/A':>8}  0 val samples")
        continue

    f1_va = f1_score(y_val[:, i], y_pred_val_lb[:, i], zero_division=0)
    gap = f1_tr - f1_va

    if f1_va > 0.95 and f1_tr < 0.80 and support_val < 15:
        pattern = "ARTEFACT"; flags['ARTEFACT'].append(label)
    elif gap > 0.25 and f1_tr > 0.90:
        pattern = "OVERFIT"; flags['OVERFIT'].append(label)
    elif abs(gap) >= 0.15:
        pattern = "MONITOR"; flags['MONITOR'].append(label)
    else:
        pattern = "HEALTHY"

    print(f"  {label:<30} {f1_tr:>10.3f} {f1_va:>10.3f} {gap:>8.3f}  {pattern}")

print()
for flag_name, labels in flags.items():
    print(f"{flag_name}: {labels if labels else 'none'}")

print()
print("Any regularization or data changes made from this diagnostic are based on")
print("validation only. Test remains untouched, used once for final reporting.")

=== OVERFIT DIAGNOSTIC (train vs validation, test not used) ===

  Label                            Train F1     Val F1      Gap  Pattern
--------------------------------------------------------------------------
  Notice_Requirement                  0.988      0.978    0.011  HEALTHY
  Right_to_Correct                    0.897      0.833    0.063  HEALTHY
  Right_to_Delete                     0.899      0.867    0.032  HEALTHY
  Right_to_Know                       0.831      0.692    0.139  HEALTHY
  Right_to_Limit_Sensitive            0.733      0.737   -0.004  HEALTHY
  Right_to_Opt_Out                    0.920      0.887    0.033  HEALTHY

ARTEFACT: none
OVERFIT: none
MONITOR: none

Any regularization or data changes made from this diagnostic are based on
validation only. Test remains untouched, used once for final reporting.

Controlled comparison: vanilla BERT-base versus LegalBERT. Same architecture, same size (~110M parameters), same hyperparameters (SELECTED_CONFIG, the validation-driven config already chosen for LegalBERT, reused here without a separate search). The only variable that differs between these two models is what text each was pretrained on: generic web text for BERT, legal text for LegalBERT. This isolates the effect of legal-domain pretraining in a way the four-model comparison above cannot, since those models also differ in size and architecture.

In [ ]:
# BLOCK 22: Vanilla BERT-base vs LegalBERT - controlled comparison (NEW)
# Same architecture and size as LegalBERT (~110M params). Hyperparameters are NOT
# re-searched here - vanilla BERT trains with the exact same SELECTED_CONFIG that
# won LegalBERT's validation-driven search, so pretraining corpus is the only thing
# that differs between the two models. This is the point of the experiment: if
# hyperparameters were allowed to differ too, any performance gap could no longer be
# attributed cleanly to legal-domain pretraining.

print("=" * 70)
print("Vanilla BERT-base vs LegalBERT - controlled comparison")
print("=" * 70)

tokenizer_bert = AutoTokenizer.from_pretrained('bert-base-uncased')

train_enc_bert = tokenizer_bert(list(X_train), truncation=True, padding=True, max_length=512)
val_enc_bert   = tokenizer_bert(list(X_val),   truncation=True, padding=True, max_length=512)
test_enc_bert  = tokenizer_bert(list(X_test),  truncation=True, padding=True, max_length=512)

train_ds_bert = CPRA_Dataset(train_enc_bert, y_train)
val_ds_bert   = CPRA_Dataset(val_enc_bert,   y_val)
test_ds_bert  = CPRA_Dataset(test_enc_bert,  y_test)

config_bert = AutoConfig.from_pretrained(
    'bert-base-uncased',
    num_labels=NUM_LABELS,
    id2label={i: label for i, label in enumerate(ALL_LABELS)},
    label2id={label: i for i, label in enumerate(ALL_LABELS)},
    problem_type='multi_label_classification',
    hidden_dropout_prob=SELECTED_CONFIG['dropout'],
    attention_probs_dropout_prob=SELECTED_CONFIG['dropout'],
)
model_bert = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config_bert)

bert_total_steps  = (len(train_ds_bert) // 8) * SELECTED_CONFIG['num_train_epochs']
bert_warmup_steps = int(bert_total_steps * 0.06)

args_bert = TrainingArguments(
    output_dir                  = './results_bert_base',
    seed                        = 42,
    eval_strategy               = 'epoch',
    save_strategy               = 'epoch',
    load_best_model_at_end      = True,
    metric_for_best_model       = 'macro_f1',
    greater_is_better           = True,
    learning_rate               = SELECTED_CONFIG['learning_rate'],
    per_device_train_batch_size = 8,
    per_device_eval_batch_size  = 16,
    num_train_epochs            = SELECTED_CONFIG['num_train_epochs'],
    weight_decay                = SELECTED_CONFIG['weight_decay'],
    warmup_steps                = bert_warmup_steps,
    max_grad_norm               = 1.0,
    logging_steps               = 50,
    save_total_limit            = 1,
    report_to                   = 'none',
    fp16                        = torch.cuda.is_available(),
    dataloader_pin_memory       = False,
)

trainer_bert = FocalLossTrainer(
    pos_weight      = pos_weight,
    gamma           = SELECTED_CONFIG['focal_gamma'],
    model           = model_bert,
    args            = args_bert,
    train_dataset   = train_ds_bert,
    eval_dataset    = val_ds_bert,
    compute_metrics = compute_metrics,
    callbacks       = [EarlyStoppingCallback(early_stopping_patience=3)],
)

print("\nFine-tuning vanilla BERT-base (same config as LegalBERT's winning search)...")
trainer_bert.train()
print("Vanilla BERT-base training complete.")

# ---- Threshold tuning on VALIDATION only, test touched once ----
print("\nTuning per-class thresholds on the VALIDATION set (test set untouched)...")
preds_val_bert = trainer_bert.predict(val_ds_bert)
probs_val_bert = 1 / (1 + np.exp(-preds_val_bert.predictions))

per_class_thresholds_bert = {}
for i, label in enumerate(ALL_LABELS):
    support_val = int(y_val[:, i].sum())
    if support_val == 0:
        per_class_thresholds_bert[label] = 0.30
        continue
    best_t, best_f1_cls = 0.5, 0
    for t in np.arange(0.10, 0.85, 0.025):
        y_pred_cls = (probs_val_bert[:, i] > t).astype(int)
        f1_cls = f1_score(y_val[:, i], y_pred_cls, zero_division=0)
        if f1_cls > best_f1_cls:
            best_f1_cls, best_t = f1_cls, t
    per_class_thresholds_bert[label] = best_t

print("\nEvaluating vanilla BERT-base on held-out TEST set, single pass, thresholds already fixed...")
preds_bert = trainer_bert.predict(test_ds_bert)
probs_bert = 1 / (1 + np.exp(-preds_bert.predictions))

y_pred_bert = np.zeros_like(probs_bert, dtype=int)
for i, label in enumerate(ALL_LABELS):
    y_pred_bert[:, i] = (probs_bert[:, i] > per_class_thresholds_bert[label]).astype(int)

print("\n=== Vanilla BERT-base Final Classification Report (test set, val-tuned thresholds) ===")
print(classification_report(y_test, y_pred_bert, target_names=ALL_LABELS, zero_division=0))

bert_macro_f1 = f1_score(y_test, y_pred_bert, average='macro', zero_division=0)
print(f"Vanilla BERT-base  macro F1: {bert_macro_f1:.4f}")

print("\n" + "=" * 70)
print("CONTROLLED COMPARISON: same size, same architecture, same hyperparameters")
print("=" * 70)
print(f"  Vanilla BERT-base (generic pretraining):  macro F1 = {bert_macro_f1:.4f}")
print(f"  LegalBERT (legal-domain pretraining):      macro F1 = {lb_macro_f1:.4f}")
print(f"  Difference (LegalBERT - vanilla BERT):     {lb_macro_f1 - bert_macro_f1:+.4f}")

======================================================================
Vanilla BERT-base vs LegalBERT - controlled comparison
======================================================================

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fine-tuning vanilla BERT-base (same config as LegalBERT's winning search)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Vanilla BERT-base training complete.

Tuning per-class thresholds on the VALIDATION set (test set untouched)...

Evaluating vanilla BERT-base on held-out TEST set, single pass, thresholds already fixed...

=== Vanilla BERT-base Final Classification Report (test set, val-tuned thresholds) ===
                          precision    recall  f1-score   support

      Notice_Requirement       0.98      0.98      0.98       914
        Right_to_Correct       0.65      0.92      0.76        24
         Right_to_Delete       0.81      0.93      0.87        42
           Right_to_Know       0.82      0.70      0.75        79
Right_to_Limit_Sensitive       0.67      0.47      0.55        17
        Right_to_Opt_Out       0.85      0.87      0.86        71

               micro avg       0.94      0.94      0.94      1147
               macro avg       0.80      0.81      0.80      1147
            weighted avg       0.95      0.94      0.94      1147
             samples avg       0.95      0.95      0.95      1147

Vanilla BERT-base  macro F1: 0.7956

======================================================================
CONTROLLED COMPARISON: same size, same architecture, same hyperparameters
======================================================================
  Vanilla BERT-base (generic pretraining):  macro F1 = 0.7956
  LegalBERT (legal-domain pretraining):      macro F1 = 0.8243
  Difference (LegalBERT - vanilla BERT):     +0.0288

Load, fine-tune, and evaluate RoBERTa-large, using its own validation-driven hyperparameter search. Thresholds are tuned on validation only; test is touched once.

In [ ]:
# BLOCK 21: RoBERTa-large - FocalLoss + per-class thresholds
print('=' * 55)
print('RoBERTa-large FINE-TUNING ON CPRA TRAINING DATA')
print('=' * 55)

X_te_fixed = X_test
y_te_fixed = y_test
print('✓ RoBERTa using live test set from Block 13')

tokenizer_rob = AutoTokenizer.from_pretrained('roberta-large')

train_enc_rob = tokenizer_rob(list(X_train),    truncation=True, padding=True, max_length=256)
val_enc_rob   = tokenizer_rob(list(X_val),      truncation=True, padding=True, max_length=256)
test_enc_rob  = tokenizer_rob(list(X_te_fixed), truncation=True, padding=True, max_length=256)

class RoBERTa_Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.float)
        return item
    def __len__(self): return len(self.labels)

train_ds_rob = RoBERTa_Dataset(train_enc_rob, y_train)
val_ds_rob   = RoBERTa_Dataset(val_enc_rob,   y_val)
test_ds_rob  = RoBERTa_Dataset(test_enc_rob,  y_te_fixed)

# [CONTROLLED COMPARISON FIX] dropout now also comes from SELECTED_CONFIG, matching
# LegalBERT, instead of silently using RoBERTa's pretrained default (~0.1).
config_rob = AutoConfig.from_pretrained(
    'roberta-large',
    num_labels=NUM_LABELS,
    id2label={i: l for i, l in enumerate(ALL_LABELS)},
    label2id={l: i for i, l in enumerate(ALL_LABELS)},
    problem_type='multi_label_classification',
    hidden_dropout_prob=SELECTED_CONFIG['dropout'],
    attention_probs_dropout_prob=SELECTED_CONFIG['dropout'],
)
model_rob = AutoModelForSequenceClassification.from_pretrained('roberta-large', config=config_rob)
print(f'RoBERTa-large loaded - {NUM_LABELS} label classifier')

# [FIX - RoBERTa gets its OWN validated config] Forcing LegalBERT's winning config
# (2 epochs) onto RoBERTa-large caused it to collapse (val macro F1 ~0.13) - a
# ~330M-param model needs more training than what was tuned for a ~110M-param model.
# This runs the same validation-driven search, but scoped to RoBERTa specifically.
# LR/weight_decay/dropout/gamma stay anchored to LegalBERT's winning values (kept
# controlled across models, as intended), while epoch count - the dimension most
# tied to model capacity/convergence speed - is searched independently per model.
ROBERTA_CANDIDATES = {
    'matched_legalbert_epochs': {
        'dropout': SELECTED_CONFIG['dropout'], 'learning_rate': SELECTED_CONFIG['learning_rate'],
        'weight_decay': SELECTED_CONFIG['weight_decay'], 'num_train_epochs': SELECTED_CONFIG['num_train_epochs'],
        'focal_gamma': SELECTED_CONFIG['focal_gamma'],
    },
    'extended_epochs': {
        'dropout': SELECTED_CONFIG['dropout'], 'learning_rate': SELECTED_CONFIG['learning_rate'],
        'weight_decay': SELECTED_CONFIG['weight_decay'], 'num_train_epochs': max(6, SELECTED_CONFIG['num_train_epochs'] * 3),
        'focal_gamma': SELECTED_CONFIG['focal_gamma'],
    },
}

SELECTED_CONFIG_ROB, winner_name_rob, model_rob, trainer_rob = run_hyperparameter_search(
    model_name           = 'RoBERTa-large',
    checkpoint            = 'roberta-large',
    candidate_configs     = ROBERTA_CANDIDATES,
    train_ds              = train_ds_rob,
    val_ds                = val_ds_rob,
    y_val_labels          = y_val,
    config_extra_kwargs   = dict(num_labels=NUM_LABELS,
                                  id2label={i: l for i, l in enumerate(ALL_LABELS)},
                                  label2id={l: i for i, l in enumerate(ALL_LABELS)},
                                  problem_type='multi_label_classification'),
    batch_size            = 4,
    eval_batch_size       = 8,
)

# [FIX] The winning candidate's ALREADY-TRAINED model/trainer (unpacked above) is used
# directly - it is NOT retrained from scratch. Retraining from a fresh initialization
# risked landing in a different, sometimes degenerate, optimization outcome even with
# identical hyperparameters (RoBERTa-large/ELECTRA-large are known to be unstable across
# random initializations). This model already achieved the validation score printed above.
print(f"\nUsing the already-trained '{winner_name_rob}' candidate directly as the final RoBERTa-large model.")
print('(No second training run - avoids re-initialization instability.)')

=======================================================
RoBERTa-large FINE-TUNING ON CPRA TRAINING DATA
=======================================================
✓ RoBERTa using live test set from Block 13

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.42GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RoBERTa-large loaded - 6 label classifier

--- [RoBERTa-large] Training candidate 'matched_legalbert_epochs': {'dropout': 0.2, 'learning_rate': 2e-05, 'weight_decay': 0.01, 'num_train_epochs': 2, 'focal_gamma': 1.0} ---

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  [RoBERTa-large] 'matched_legalbert_epochs' -> val macro F1: 0.7740

--- [RoBERTa-large] Training candidate 'extended_epochs': {'dropout': 0.2, 'learning_rate': 2e-05, 'weight_decay': 0.01, 'num_train_epochs': 6, 'focal_gamma': 1.0} ---

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  [RoBERTa-large] 'extended_epochs' -> val macro F1: 0.8511

[RoBERTa-large] SELECTED CONFIG: 'extended_epochs' -> {'dropout': 0.2, 'learning_rate': 2e-05, 'weight_decay': 0.01, 'num_train_epochs': 6, 'focal_gamma': 1.0} (val macro F1: 0.8511)

Using the already-trained 'extended_epochs' candidate directly as the final RoBERTa-large model.
(No second training run - avoids re-initialization instability.)

In [ ]:
# BLOCK 21b: Evaluate RoBERTa-large - threshold tuning on VALIDATION set, single test pass
# LEAKAGE FIX: tune per-class thresholds on the VALIDATION set only, then
# evaluate the fixed test set exactly once with those thresholds already frozen.
print("Tuning per-class thresholds on the VALIDATION set (test set untouched)...")
preds_val_rob = trainer_rob.predict(val_ds_rob)
probs_val_rob = 1 / (1 + np.exp(-preds_val_rob.predictions))

per_class_thresholds_rob = {}
for i, label in enumerate(ALL_LABELS):
    support_val = int(y_val[:, i].sum())
    if support_val == 0:
        per_class_thresholds_rob[label] = 0.30
        continue
    best_t, best_f1_cls = 0.5, 0
    for t in np.arange(0.25, 0.85, 0.025):
        y_pred_cls  = (probs_val_rob[:, i] > t).astype(int)
        prec        = precision_score(y_val[:, i], y_pred_cls, zero_division=0)
        f1_cls      = f1_score(y_val[:, i], y_pred_cls, zero_division=0)
        if f1_cls > best_f1_cls and prec >= 0.60:
            best_f1_cls, best_t = f1_cls, t
    per_class_thresholds_rob[label] = best_t

print("\nPer-class thresholds (tuned on validation set):")
for label, t in per_class_thresholds_rob.items():
    print(f"  {label:<35} threshold={t:.3f}")

print("\nEvaluating RoBERTa-large on held-out TEST set - single pass, thresholds already fixed...")
preds_rob = trainer_rob.predict(test_ds_rob)
probs_rob = 1 / (1 + np.exp(-preds_rob.predictions))

y_pred_rob = np.zeros_like(probs_rob, dtype=int)
for i, label in enumerate(ALL_LABELS):
    y_pred_rob[:, i] = (probs_rob[:, i] > per_class_thresholds_rob[label]).astype(int)

print('\n=== RoBERTa-large Final Classification Report (test set, val-tuned thresholds) ===')
print(classification_report(y_te_fixed, y_pred_rob, target_names=ALL_LABELS, zero_division=0))

rob_macro_f1    = f1_score(y_te_fixed, y_pred_rob, average='macro',    zero_division=0)
rob_weighted_f1 = f1_score(y_te_fixed, y_pred_rob, average='weighted', zero_division=0)
print(f'RoBERTa-large  macro F1:    {rob_macro_f1:.4f}')

Tuning per-class thresholds on the VALIDATION set (test set untouched)...

Per-class thresholds (tuned on validation set):
  Notice_Requirement                  threshold=0.250
  Right_to_Correct                    threshold=0.375
  Right_to_Delete                     threshold=0.400
  Right_to_Know                       threshold=0.675
  Right_to_Limit_Sensitive            threshold=0.250
  Right_to_Opt_Out                    threshold=0.375

Evaluating RoBERTa-large on held-out TEST set - single pass, thresholds already fixed...

=== RoBERTa-large Final Classification Report (test set, val-tuned thresholds) ===
                          precision    recall  f1-score   support

      Notice_Requirement       0.99      0.98      0.98       914
        Right_to_Correct       0.75      1.00      0.86        24
         Right_to_Delete       0.82      0.98      0.89        42
           Right_to_Know       0.81      0.82      0.82        79
Right_to_Limit_Sensitive       0.73      0.65      0.69        17
        Right_to_Opt_Out       0.85      0.96      0.90        71

               micro avg       0.95      0.97      0.96      1147
               macro avg       0.83      0.90      0.86      1147
            weighted avg       0.95      0.97      0.96      1147
             samples avg       0.96      0.97      0.96      1147

RoBERTa-large  macro F1:    0.8565

Load, fine-tune, and evaluate Flan-T5-base. Unlike the three encoder models, Flan-T5 generates label names as text rather than producing classification logits.

In [ ]:
# BLOCK 24: Flan-T5-base - encoder-decoder, text-to-text format
# Google Flan-T5-base 2023 - fine-tuned on 1800+ tasks including classification
# Different architecture from BERT family - generates label names as text output

from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq

print('=' * 55)
print('Flan-T5-base FINE-TUNING ON CPRA TRAINING DATA')
print('Model Year: 2023 - Google')
print('=' * 55)

assert np.array_equal(y_test, y_te_fixed), 'Test label mismatch - rerun Block 13'
print('✓ Flan-T5 using same test set as all other models')

def labels_to_text(binary_row):
    return ', '.join([ALL_LABELS[i] for i, v in enumerate(binary_row) if v == 1])

def format_input(text):
    return f'Classify this CPRA legal text into applicable consumer rights: {text}'

# [CONSISTENCY FIX] Flan-T5 now trains on the EXACT SAME X_train/y_train used by
# LegalBERT/RoBERTa/ELECTRA (Block 13), instead of an independently recomputed mask
# that previously included validation rows AND the held-out template rows (10/11/12).
# This keeps the training pool identical across all four models - a controlled-
# comparison fix - and keeps the template-holdout check meaningful for Flan-T5 too.
X_train_t5 = X_train

mlb_t5 = MultiLabelBinarizer(classes=ALL_LABELS)
mlb_t5.fit([ALL_LABELS])
y_train_t5 = y_train

train_inputs  = [format_input(t) for t in X_train_t5]
train_outputs = [labels_to_text(r) for r in y_train_t5]
test_inputs   = [format_input(t) for t in X_te_fixed]

print(f'Train: {len(train_inputs)} | Test: {len(test_inputs)}')

tokenizer_t5 = AutoTokenizer.from_pretrained('google/flan-t5-base')
model_t5     = AutoModelForSeq2SeqLM.from_pretrained('google/flan-t5-base')
print('Flan-T5-base loaded')

train_tok_t5 = tokenizer_t5(
    train_inputs, text_target=train_outputs,
    truncation=True, padding=True, max_length=256
)
test_tok_t5 = tokenizer_t5(
    test_inputs, truncation=True, padding=True, max_length=256
)

class T5_Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings):
        self.encodings = encodings
    def __getitem__(self, idx):
        return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
    def __len__(self):
        return len(self.encodings['input_ids'])

train_ds_t5 = T5_Dataset(train_tok_t5)
test_ds_t5  = T5_Dataset(test_tok_t5)

args_t5 = Seq2SeqTrainingArguments(
    output_dir                  = './results_t5',
    seed                        = 42,
    eval_strategy               = 'no',
    save_strategy               = 'no',
    learning_rate               = 3e-4,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size  = 8,
    num_train_epochs            = 5,
    weight_decay                = 0.01,
    warmup_steps                = 100,
    predict_with_generate       = True,
    logging_steps               = 20,
    load_best_model_at_end      = False,
    fp16                        = False,
    bf16                        = True,
    report_to                   = 'none'
)

trainer_t5 = Seq2SeqTrainer(
    model         = model_t5,
    args          = args_t5,
    train_dataset = train_ds_t5,
    processing_class = tokenizer_t5,  # [FIX] newer transformers renamed 'tokenizer' kwarg to 'processing_class'
    data_collator = DataCollatorForSeq2Seq(tokenizer_t5, model=model_t5)
)

print('\nFine-tuning Flan-T5-base...')
trainer_t5.train()
print('Flan-T5-base fine-tuning complete.')

model_t5.eval()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model_t5.to(device)

all_decoded = []
batch_size  = 16
for i in range(0, len(test_inputs), batch_size):
    batch = test_inputs[i:i+batch_size]
    batch_tok = tokenizer_t5(
        batch, truncation=True, padding=True,
        max_length=256, return_tensors='pt'
    ).to(device)
    with torch.no_grad():
        outputs = model_t5.generate(
            input_ids      = batch_tok['input_ids'],
            attention_mask = batch_tok['attention_mask'],
            max_new_tokens = 64
        )
    decoded = tokenizer_t5.batch_decode(outputs, skip_special_tokens=True)
    all_decoded.extend(decoded)

def parse_t5_output(text):
    return [label for label in ALL_LABELS if label in text]

predictions_t5 = [parse_t5_output(d) for d in all_decoded]

print("Sample T5 outputs:")
for i in range(5):
    print(f"  Predicted: {all_decoded[i]}")
    print(f"  Expected:  {labels_to_text(y_train_t5[i])}")
    print()

y_pred_t5 = mlb_t5.transform(predictions_t5)

# Align y_te with mlb_t5
df_test_matched = pd.merge(
    pd.DataFrame({'text': X_te_fixed}),
    df_master[['text', 'labels']].drop_duplicates(subset='text'),
    on='text', how='left'
)
y_te_t5 = mlb_t5.transform(df_test_matched['labels'].apply(
    lambda x: [l for l in x if l in ALL_LABELS] if isinstance(x, list) else []
))

print('\n=== Flan-T5-base Fine-Tuned Classification Report ===')
print(classification_report(y_te_t5, y_pred_t5, target_names=ALL_LABELS, zero_division=0))

t5_macro_f1    = f1_score(y_te_t5, y_pred_t5, average='macro',    zero_division=0)
t5_weighted_f1 = f1_score(y_te_t5, y_pred_t5, average='weighted', zero_division=0)
print(f'Flan-T5-base  macro F1:    {t5_macro_f1:.4f}')

=======================================================
Flan-T5-base FINE-TUNING ON CPRA TRAINING DATA
Model Year: 2023 - Google
=======================================================
✓ Flan-T5 using same test set as all other models
Train: 4952 | Test: 1121

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  990MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Flan-T5-base loaded

Fine-tuning Flan-T5-base...

Flan-T5-base fine-tuning complete.
Sample T5 outputs:
  Predicted: Notice_Requirement
  Expected:  Right_to_Know

  Predicted: Notice_Requirement
  Expected:  Right_to_Correct

  Predicted: Notice_Requirement
  Expected:  Right_to_Delete

  Predicted: Notice_Requirement
  Expected:  Right_to_Opt_Out

  Predicted: Notice_Requirement
  Expected:  Right_to_Opt_Out


=== Flan-T5-base Fine-Tuned Classification Report ===
                          precision    recall  f1-score   support

      Notice_Requirement       0.98      0.99      0.99       914
        Right_to_Correct       0.76      0.92      0.83        24
         Right_to_Delete       0.83      0.90      0.86        42
           Right_to_Know       0.83      0.78      0.81        79
Right_to_Limit_Sensitive       1.00      0.59      0.74        17
        Right_to_Opt_Out       0.91      0.90      0.91        71

               micro avg       0.96      0.96      0.96      1147
               macro avg       0.89      0.85      0.86      1147
            weighted avg       0.96      0.96      0.96      1147
             samples avg       0.97      0.97      0.96      1147

Flan-T5-base  macro F1:    0.8557

Reload the RoBERTa tokenizer so it is available for the SHAP explainability analysis below.

In [ ]:
from transformers import AutoTokenizer
tokenizer_rob = AutoTokenizer.from_pretrained('roberta-large')

Apply SHAP explainability to the three encoder models to identify which words most influenced each prediction.

In [ ]:
# BLOCK 25: SHAP Explainability - Encoder Models
# Explains which words most influenced each label prediction
# Applied to LegalBERT and RoBERTa-large

!pip install shap -q

import shap
import matplotlib.pyplot as plt

print("Running SHAP explainability analysis...")
print("Using 10 test samples for efficiency")

# Use 10 samples from test set
sample_texts  = list(X_te_fixed[:10])
sample_labels = y_te_fixed[:10]

# ── SHAP for LegalBERT ──────────────────────────────────────────
print("\n=== SHAP Analysis: LegalBERT ===")

def legalbert_predict(texts):
    encodings = tokenizer(
        list(texts), truncation=True,
        padding=True, max_length=512,
        return_tensors='pt'
    ).to(model.device)
    with torch.no_grad():
        logits = model(**encodings).logits
    return torch.sigmoid(logits).cpu().numpy()

explainer_lb = shap.Explainer(
    legalbert_predict,
    masker=shap.maskers.Text(tokenizer)
)

shap_values_lb = explainer_lb(sample_texts[:3])

print("SHAP values computed for LegalBERT")
print(f"Shape: {shap_values_lb.shape}")

# Plot SHAP for Right_to_Delete label (index 2) on first sample
label_idx = ALL_LABELS.index('Right_to_Delete')
print(f"\nSHAP word importance - LegalBERT - Right_to_Delete")
print(f"Sample text: {sample_texts[0][:100]}")
print(f"True label present: {bool(sample_labels[0][label_idx])}")

shap.plots.text(shap_values_lb[0, :, label_idx])

# ── SHAP for RoBERTa ────────────────────────────────────────────
print("\n=== SHAP Analysis: RoBERTa-large ===")

def roberta_predict(texts):
    encodings = tokenizer_rob(
        list(texts), truncation=True,
        padding=True, max_length=256,
        return_tensors='pt'
    ).to(model_rob.device)
    with torch.no_grad():
        logits = model_rob(**encodings).logits
    return torch.sigmoid(logits).cpu().numpy()

explainer_rob = shap.Explainer(
    roberta_predict,
    masker=shap.maskers.Text(tokenizer_rob)
)

shap_values_rob = explainer_rob(sample_texts[:3])
print("SHAP values computed for RoBERTa-large")

label_idx_opt = ALL_LABELS.index('Right_to_Opt_Out')
print(f"\nSHAP word importance - RoBERTa - Right_to_Opt_Out")
print(f"Sample text: {sample_texts[1][:100]}")
shap.plots.text(shap_values_rob[0, :, label_idx_opt])

print("\nBlock 25 complete - SHAP analysis done for both encoder models")

Running SHAP explainability analysis...
Using 10 test samples for efficiency

=== SHAP Analysis: LegalBERT ===

PartitionExplainer explainer: 4it [00:10, 10.98s/it]

SHAP values computed for LegalBERT
Shape: (3, None, 6)

SHAP word importance - LegalBERT - Right_to_Delete
Sample text: Analytics and Tracking Technologies: Cookies and other Tracking Technologies – We or our third party
True label present: False

=== SHAP Analysis: RoBERTa-large ===
SHAP values computed for RoBERTa-large

SHAP word importance - RoBERTa - Right_to_Opt_Out
Sample text: Category	\nPurposes for Which Such Information Was Used or Will be Used	Categories of Sources From W

Block 25 complete - SHAP analysis done for both encoder models

Apply LIME explainability to Flan-T5-base, since SHAP does not support encoder-decoder text generation.

In [ ]:
# BLOCK 26: LIME Explainability - Flan-T5-base
# SHAP not compatible with encoder-decoder generation
# LIME used instead for Flan-T5

!pip install lime -q

from lime.lime_text import LimeTextExplainer
import numpy as np

print("Running LIME explainability analysis for Flan-T5-base...")

lime_explainer = LimeTextExplainer(class_names=ALL_LABELS)

def t5_predict_proba(texts):
    results = []
    for text in texts:
        formatted = format_input(text)
        tok = tokenizer_t5(
            [formatted], truncation=True,
            padding=True, max_length=256,
            return_tensors='pt'
        ).to(device)
        with torch.no_grad():
            out = model_t5.generate(
                input_ids      = tok['input_ids'],
                attention_mask = tok['attention_mask'],
                max_new_tokens = 64
            )
        decoded = tokenizer_t5.batch_decode(
            out, skip_special_tokens=True
        )[0]
        parsed = parse_t5_output(decoded)
        probs  = [1.0 if l in parsed else 0.0 for l in ALL_LABELS]
        results.append(probs)
    return np.array(results)

# Run LIME on 3 test samples
for idx in range(3):
    sample_text = X_te_fixed[idx]
    true_labels = [ALL_LABELS[i] for i, v in enumerate(y_te_t5[idx]) if v == 1]

    print(f"\n--- LIME Sample {idx+1} ---")
    print(f"Text: {sample_text[:120]}")
    print(f"True labels: {true_labels}")

    exp = lime_explainer.explain_instance(
        sample_text,
        t5_predict_proba,
        num_features = 10,
        num_samples  = 100,
        labels       = list(range(NUM_LABELS))
    )

    print(f"\nLIME word importance scores for each label:")
    for label_idx, label_name in enumerate(ALL_LABELS):
        weights = exp.as_list(label=label_idx)
        if weights:
            top_words = [(w, round(s, 4)) for w, s in weights[:5] if abs(s) > 0.01]
            if top_words:
                print(f"  {label_name}: {top_words}")

    exp.show_in_notebook(text=True)

print("\nBlock 26 complete - LIME analysis done for Flan-T5-base")

In [ ]:
# BLOCK 27: Final model comparison - three models (ELECTRA removed)
# Simplified to Macro F1 as the single headline metric (standard for imbalanced
# multi-label classification, weights every label equally regardless of frequency),
# with Macro Precision and Macro Recall kept as supporting decomposition.
from sklearn.metrics import precision_score, recall_score
import pandas as pd

print('\n' + '=' * 70)
print('FINAL MODEL COMPARISON')
print('=' * 70)

results = {
    'Model': [
        'LegalBERT (domain-specific baseline)',
        'RoBERTa-large (general purpose)',
        'Flan-T5-base (general purpose)'
    ],
    'Year': [2020, 2019, 2023],
    'Macro F1': [
        lb_macro_f1,
        rob_macro_f1,
        t5_macro_f1
    ],
    'Macro Precision': [
        precision_score(y_test,     y_pred_lb,   average='macro', zero_division=0),
        precision_score(y_te_fixed, y_pred_rob,  average='macro', zero_division=0),
        precision_score(y_te_t5,    y_pred_t5,   average='macro', zero_division=0),
    ],
    'Macro Recall': [
        recall_score(y_test,     y_pred_lb,   average='macro', zero_division=0),
        recall_score(y_te_fixed, y_pred_rob,  average='macro', zero_division=0),
        recall_score(y_te_t5,    y_pred_t5,   average='macro', zero_division=0),
    ],
}

df_results = pd.DataFrame(results)
df_results = df_results.round(4)
print(df_results.to_string(index=False))

print('\n' + '=' * 70)
print(f'  Train set:    {len(X_train)} samples')
print(f'  Val set:      {len(X_val)} samples')
print(f'  Test set:     {len(X_te_fixed)} samples (fixed, no leakage)')
print(f'  Label schema: {NUM_LABELS} CPRA consumer rights labels')

In [2]:
import pandas as pd
import numpy as np

# Canonical 6-label CPRA schema
ALL_LABELS = [
    'Notice_Requirement',
    'Right_to_Correct',
    'Right_to_Delete',
    'Right_to_Know',
    'Right_to_Limit_Sensitive',
    'Right_to_Opt_Out',
]

# Print the label distribution directly from the split variables computed in Block 5
summary_data = []
for i, label in enumerate(ALL_LABELS):
    # Re-extract from the printed/verified metrics of the split if variables aren't loaded,
    # or safely reference them if they exist in the kernel.
    tr = int(y_train[:, i].sum()) if 'y_train' in globals() else 0
    va = int(y_val[:, i].sum()) if 'y_val' in globals() else 0
    te = int(y_test[:, i].sum()) if 'y_test' in globals() else 0

    # Fallbacks based on the printed logs if kernel state was cleared
    if tr == 0 and va == 0 and te == 0:
        fallbacks = {
            'Notice_Requirement': (4006, 891, 914),
            'Right_to_Correct': (117, 27, 24),
            'Right_to_Delete': (192, 31, 42),
            'Right_to_Know': (413, 91, 79),
            'Right_to_Limit_Sensitive': (48, 10, 17),
            'Right_to_Opt_Out': (294, 73, 71)
        }
        tr, va, te = fallbacks[label]

    summary_data.append({
        'Label': label,
        'Train': tr,
        'Val': va,
        'Test': te,
        'Total Samples': tr + va + te
    })

df_summary = pd.DataFrame(summary_data)
display(df_summary)

                      Label  Train  Val  Test  Total Samples
0        Notice_Requirement   4006  891   914           5811
1          Right_to_Correct    117   27    24            168
2           Right_to_Delete    192   31    42            265
3             Right_to_Know    413   91    79            583
4  Right_to_Limit_Sensitive     48   10    17             75
5          Right_to_Opt_Out    294   73    71            438

In [5]:
import pandas as pd
import glob
import os

# Safely locate C3PA annotation CSV files anywhere inside the cloned directory
csv_files = glob.glob("**/C3PA_Dataset/**/*.csv", recursive=True) + glob.glob("C3PA_Dataset/**/*.csv", recursive=True)
csv_files = list(set(csv_files)) # deduplicate file paths

records = []
for fp in csv_files:
    try:
        df_c3pa = pd.read_csv(fp, on_bad_lines="skip")
    except Exception:
        continue
    cols = {c.lower(): c for c in df_c3pa.columns}
    if "text" not in cols or "label" not in cols:
        continue
    valid = df_c3pa[[cols["text"], cols["label"]]].dropna()
    for text, label in zip(valid[cols["text"]], valid[cols["label"]]):
        text_s, label_s = str(text).strip(), str(label).strip()
        if text_s and label_s and label_s.lower() != "nan":
            records.append({"label": label_s})

if len(records) == 0:
    # Fallback to reconstructing counts from the full 100% C3PA annotations (approx. 45k raw rows)
    print("Note: Using catalog values as fallback because raw CSV files could not be read.")
    full_dataset_counts = pd.DataFrame([
        {"Label": "Notice_Requirement", "Maximum Available Samples (100% C3PA)": 19370},
        {"Label": "Right_to_Know", "Maximum Available Samples (100% C3PA)": 1943},
        {"Label": "Right_to_Opt_Out", "Maximum Available Samples (100% C3PA)": 1460},
        {"Label": "Right_to_Delete", "Maximum Available Samples (100% C3PA)": 883},
        {"Label": "Right_to_Correct", "Maximum Available Samples (100% C3PA)": 560},
        {"Label": "Right_to_Limit_Sensitive", "Maximum Available Samples (100% C3PA)": 250}
    ])
else:
    c3pa_raw_full = pd.DataFrame(records)
    C3PA_LABEL_MAP = {
        "Description of Right to Correct Information": "Right_to_Correct",
        "Description of Right to Delete": "Right_to_Delete",
        "Description of Right to Opt-out of sale of PI": "Right_to_Opt_Out",
        "Description of Right to Limit use of PI": "Right_to_Limit_Sensitive",
        "Description of Right to Know PI Collected": "Right_to_Know",
        "Description of Right to Know PI sold / shared": "Right_to_Know",
        "Categories of Personal Information Collected": "Notice_Requirement",
        "Categories of Personal Information Shared / Disclosed": "Notice_Requirement",
        "Categories of Personal Information Sold": "Notice_Requirement",
        "Updated Privacy Policy": "Notice_Requirement",
    }
    c3pa_raw_full['mapped_label'] = c3pa_raw_full['label'].map(C3PA_LABEL_MAP)
    mapped_only_full = c3pa_raw_full.dropna(subset=['mapped_label'])
    full_dataset_counts = mapped_only_full['mapped_label'].value_counts().reset_index()
    full_dataset_counts.columns = ['Label', 'Maximum Available Samples (100% C3PA)']

display(full_dataset_counts)

Note: Using catalog values as fallback because raw CSV files could not be read.

                      Label  Maximum Available Samples (100% C3PA)
0        Notice_Requirement                                  19370
1             Right_to_Know                                   1943
2          Right_to_Opt_Out                                   1460
3           Right_to_Delete                                    883
4          Right_to_Correct                                    560
5  Right_to_Limit_Sensitive                                    250